name: Publicar no NuGet
on:
  release:
    types: [created]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore src/WebmaniaBR.AI.Validation.csproj
    - name: Build
      run: dotnet build src/WebmaniaBR.AI.Validation.csproj --configuration Release --no-restore
    - name: Pack
      run: dotnet pack src/WebmaniaBR.AI.Validation.csproj --configuration Release --no-build -p:PackageVersion=${{ github.ref_name }} -p:Version=${{ github.ref_name }}
    - name: Push to NuGet
      run: dotnet nuget push "src/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"